export enum FieldCode {
  MISSED = 'MISSED',
  UNPROCESSABLE = 'UNPROCESSABLE',
  NOT_UNIQUE = 'NOT_UNIQUE',
  REQUIRED = 'REQUIRED',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  EXPIRED = 'EXPIRED',
  MALFORMED = 'MALFORMED',
}
